import Navigation from "@/components/Navigation"; // Esto es una ruta absoluta
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://bootswatch.com/5/morph/bootstrap.min.css"
        />
      </head>
      <body className={inter.className}>
        <Navigation />
        <div className="container" style={{ marginTop: "3rem" }}>
          {children}
        </div>
      </body>
    </html>
  );
}
